### ISSUE TITLE
Multiple classes applied to a component using :classes on "ul" element

### ISSUE THREAD

**Issue by zmiKaminski** [TahaSh/vue-paginate#31]
Hey,

I am attempting to supply multiple class names when defining custom classes to pass into the `<paginate-links>` component for the 'ul' element on version 3.2.2.

### This works:
`<paginate-links for="whatever" :classes="{ 'ul': ['pagination'] }">`

Result: `class="pagination"`

### This does not work:
`<paginate-links for="whatever" :classes="{ 'ul': ['pagination pagination-sm'] }">`

Result: 
```
Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('pagination pagination-sm') contains HTML space characters, which are not valid in tokens.
    at http://localhost:3000/resources/assets/javascripts/bundle.js:15893:35
    at Array.forEach (native)
    at addAdditionalClasses (http://localhost:3000/resources/assets/javascripts/bundle.js:15891:27)
    at Array.<anonymous> (http://localhost:3000/resources/assets/javascripts/bundle.js:15775:12)
    at nextTickHandler (http://localhost:3000/resources/assets/javascripts/bundle.js:10727:19)
```

### This does not work:
`<paginate-links for="whatever" :classes="{ 'ul': ['pagination', 'pagination-sm'] }">`

Result: `class="pagination,pagination-sm"`

I see in the code where the issue is but I am unable to make a PR at this time.  It appears to be on lines 213-214 in PaginateLinks.  The 'ul' appears to be the only element affected.

**Great component btw.  Thank you.**

**Comment by zmiKaminski** [comment]
Thank you!
